# Generated by Django 3.0.4 on 2020-07-12 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(choices=[('AB', 'Stockholm'), ('AC', 'Västerbotten'), ('BD', 'Norrbotten'), ('C', 'Uppsala'), ('D', 'Södermanland'), ('E', 'Östergötland'), ('F', 'Jönköping'), ('G', 'Kronoberg'), ('H', 'Kalmar'), ('I', 'Gotland'), ('K', 'Blekinge'), ('M', 'Skåne'), ('N', 'Halland'), ('O', 'Västra Götaland'), ('S', 'Värmland'), ('T', 'Örebro'), ('U', 'Västmanland'), ('W', 'Dalarna'), ('X', 'Gävleborg'), ('Y', 'Västernorrland'), ('Z', 'Jämtland')], max_length=120),
        ),
        migrations.CreateModel(
            name='UserDefaultAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address_billing_default', to='accounts.UserAddress')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address_shipping_default', to='accounts.UserAddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
